worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        location / {
            proxy_pass https://www.ddizi.im;
            
            proxy_set_header Host www.ddizi.im;
            proxy_set_header Referer https://www.ddizi.im;
            proxy_set_header User-Agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";
            
            proxy_set_header Accept-Encoding "";
            proxy_buffering off;
            proxy_request_buffering off;
            
            sub_filter 'https://www.ddizi.im' 'https://x3nc1-proxy.onrender.com';
            sub_filter 'http://www.ddizi.im' 'https://x3nc1-proxy.onrender.com';
            sub_filter 'www.ddizi.im' 'x3nc1-proxy.onrender.com';
            sub_filter_once off;
            sub_filter_types text/html text/css application/javascript application/vnd.apple.mpegurl;
        }
    }
}
